import a34_exception
import math
a34_exception.Myerror

def main():
    print(math.tan(30/180*math.pi))
    print(math.sin(30/180*math.pi))

if __name__ == "__main__":  
    # 직접 실행 시_main 함수 호출
    # Call main function when executed directly  
    main() 
